version: 1.0.{build}
install:
- cmd: npm install -g qunitjs
- cmd: npm install -g jsdoc
- cmd: npm install -g complexity-report
- cmd: npm install -g jshint

build_script:
- cmd: cr C:\projects\penguin2d\scripts\about.js C:\projects\penguin2d\scripts\background.js C:\projects\penguin2d\scripts\game.js C:\projects\penguin2d\scripts\gameOver.js C:\projects\penguin2d\scripts\healthBar.js C:\projects\penguin2d\scripts\icecream.js C:\projects\penguin2d\scripts\iceHole.js C:\projects\penguin2d\scripts\menu.js C:\projects\penguin2d\scripts\penguin.js C:\projects\penguin2d\scripts\pieceOfIce.js C:\projects\penguin2d\scripts\rock.js C:\projects\penguin2d\scripts\rules.js C:\projects\penguin2d\scripts\scoreBar.js C:\projects\penguin2d\scripts\snowdrift.js C:\projects\penguin2d\scripts\snowflake.js C:\projects\penguin2d\scripts\sprite.js C:\projects\penguin2d\scripts\walrus.js > stat_analysis.txt
- cmd: jsdoc C:\projects\penguin2d\scripts\about.js C:\projects\penguin2d\scripts\background.js C:\projects\penguin2d\scripts\game.js C:\projects\penguin2d\scripts\gameOver.js C:\projects\penguin2d\scripts\healthBar.js C:\projects\penguin2d\scripts\icecream.js C:\projects\penguin2d\scripts\iceHole.js C:\projects\penguin2d\scripts\menu.js C:\projects\penguin2d\scripts\penguin.js C:\projects\penguin2d\scripts\pieceOfIce.js C:\projects\penguin2d\scripts\rock.js C:\projects\penguin2d\scripts\rules.js C:\projects\penguin2d\scripts\scoreBar.js C:\projects\penguin2d\scripts\snowdrift.js C:\projects\penguin2d\scripts\snowflake.js C:\projects\penguin2d\scripts\sprite.js C:\projects\penguin2d\scripts\walrus.js
- cmd: jshint C:\projects\penguin2d\scripts\about.js C:\projects\penguin2d\scripts\background.js C:\projects\penguin2d\scripts\game.js C:\projects\penguin2d\scripts\gameOver.js C:\projects\penguin2d\scripts\healthBar.js C:\projects\penguin2d\scripts\icecream.js C:\projects\penguin2d\scripts\iceHole.js C:\projects\penguin2d\scripts\menu.js C:\projects\penguin2d\scripts\penguin.js C:\projects\penguin2d\scripts\pieceOfIce.js C:\projects\penguin2d\scripts\rock.js C:\projects\penguin2d\scripts\rules.js C:\projects\penguin2d\scripts\scoreBar.js C:\projects\penguin2d\scripts\snowdrift.js C:\projects\penguin2d\scripts\snowflake.js C:\projects\penguin2d\scripts\sprite.js C:\projects\penguin2d\scripts\walrus.js > metrics.txt

artifacts:
- path: C:\projects\penguin2d\scripts\metrics.txt
  name: Metrics
  type: WebDeployPackage
- path: C:\projects\penguin2d\scripts\stat_analysis.txt
  name: StatAnalysis
  type: WebDeployPackage
- path: C:\projects\penguin2d\out
  name: Documentation
  type: WebDeployPackage
